# SPDX-License-Identifier: Apache-2.0
PROGRAM = pipesense_multiphase
PROGRAM_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
EXTRA_SRCS := sequential_phase.S

include ${PROGRAM_DIR}/../common/common.mk
