#!/usr/bin/env python3
"""Generate deterministic constrained-random checks for the Ibex integration."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_C = ROOT / "integrations" / "ibex" / "sw" / "pipesense_fuzz" / "pipesense_fuzz.c"
DEFAULT_CSV = ROOT / "integrations" / "ibex" / "verif" / "fuzz_expected.csv"
MASK = 0xFFFF_FFFF


def rotl(value: int, amount: int) -> int:
    return ((value << amount) | (value >> (32 - amount))) & MASK


def run_seed(seed: int) -> int:
    memory = [((seed + index) * 0x45D9F3B) & MASK for index in range(16)]
    value = (seed * 0x9E3779B9 + 0x7F4A7C15) & MASK
    for index in range(128):
        mixed = value
        mixed ^= mixed << 13 & MASK
        mixed ^= mixed >> 17
        mixed ^= mixed << 5 & MASK
        mixed &= MASK
        if mixed & 1:
            value = rotl((mixed + 0x6D2B79F5) & MASK, index % 31 + 1)
        else:
            value = (mixed * 1_664_525 + 1_013_904_223) & MASK
        slot = index & 15
        memory[slot] = value ^ memory[(index + 5) & 15]
        value ^= memory[(index + 11) & 15]
        value &= MASK
    for word in memory:
        value = rotl(value ^ word, 7)
    return value


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seeds", type=int, default=500)
    parser.add_argument("--c-output", type=Path, default=DEFAULT_C)
    parser.add_argument("--csv-output", type=Path, default=DEFAULT_CSV)
    args = parser.parse_args()
    if args.seeds < 1:
        parser.error("--seeds must be positive")

    signatures = [run_seed(seed) for seed in range(args.seeds)]
    aggregate = 0
    for signature in signatures:
        aggregate = rotl(aggregate ^ signature, 3)

    args.c_output.parent.mkdir(parents=True, exist_ok=True)
    constants = ",\n  ".join(f"0x{value:08x}u" for value in signatures)
    source = f'''// Generated by scripts/generate_ibex_fuzz.py --seeds {args.seeds}.
// SPDX-License-Identifier: Apache-2.0
#include "simple_system_common.h"

#define SEED_COUNT {args.seeds}u

static const uint32_t expected[SEED_COUNT] = {{
  {constants}
}};

static uint32_t rotl32(uint32_t value, uint32_t amount) {{
  return (value << amount) | (value >> (32u - amount));
}}

static uint32_t run_seed(uint32_t seed) {{
  uint32_t memory[16];
  uint32_t value = seed * 0x9e3779b9u + 0x7f4a7c15u;
  for (uint32_t index = 0; index < 16; ++index)
    memory[index] = (seed + index) * 0x045d9f3bu;
  for (uint32_t index = 0; index < 128; ++index) {{
    uint32_t mixed = value;
    mixed ^= mixed << 13;
    mixed ^= mixed >> 17;
    mixed ^= mixed << 5;
    if (mixed & 1u)
      value = rotl32(mixed + 0x6d2b79f5u, index % 31u + 1u);
    else
      value = mixed * 1664525u + 1013904223u;
    memory[index & 15u] = value ^ memory[(index + 5u) & 15u];
    value ^= memory[(index + 11u) & 15u];
  }}
  for (uint32_t index = 0; index < 16; ++index)
    value = rotl32(value ^ memory[index], 7u);
  return value;
}}

int main(void) {{
  uint32_t aggregate = 0;
  pcount_enable(0);
  pcount_reset();
  pcount_enable(1);
  for (uint32_t seed = 0; seed < SEED_COUNT; ++seed) {{
    uint32_t signature = run_seed(seed);
    if (signature != expected[seed]) {{
      pcount_enable(0);
      puts("PIPESENSE_FUZZ_FAIL seed=");
      puthex(seed);
      putchar('\\n');
      while (1) {{}}
    }}
    aggregate = rotl32(aggregate ^ signature, 3u);
  }}
  pcount_enable(0);
  if (aggregate != 0x{aggregate:08x}u)
    while (1) {{}}
  puts("PIPESENSE_FUZZ_PASS seeds={args.seeds} signature=");
  puthex(aggregate);
  putchar('\\n');
  return 0;
}}
'''
    args.c_output.write_text(source, encoding="ascii", newline="\n")

    args.csv_output.parent.mkdir(parents=True, exist_ok=True)
    with args.csv_output.open("w", encoding="ascii", newline="") as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow(["seed", "expected_signature"])
        writer.writerows((seed, f"0x{signature:08x}")
                         for seed, signature in enumerate(signatures))
    print(f"Generated {args.seeds} seeds; aggregate=0x{aggregate:08x}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
